version: '3.8'

services:
  database:
    image: postgres:15-alpine
    container_name: kampus_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  backend:
    image: kampus:latest
    container_name: kampus_backend
    build:
      context: .
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=${POSTGRES_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - USER_USERNAME=${BACKEND_USERNAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
    ports:
      - "8080:8080"

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./dist:/var/www/frontend:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend

