version: '3.9'

services:
  database:
    image: postgres:15-alpine
    container_name: kampus_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  backend:
    image: kampus:latest
    container_name: kampus_backend
    build:
      context: .
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=${POSTGRES_URL}
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - "8080:8080"


#version: '3.9'
#
#services:
#  db:
#    image: postgres:15-alpine
#    container_name: kampus_db
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: postgres
#    ports:
#      - "5432:5432"
#
#  backend:
#    image: kampus:latest
#    build:
#      context: .
#    depends_on:
#      - db
#    environment:
#      - SPRING_DATASOURCE_URL=${POSTGRES_URL}
#      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
#      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#    ports:
#      - "8080:8080"