create TABLE ${flyway:defaultSchema}.students
(
    students_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name      VARCHAR(255),
    last_name       VARCHAR(255),
    middle_name     VARCHAR(255),
    date_birth      Date,
    university_name VARCHAR(255),
    course_title    VARCHAR(255),
    course_number   INTEGER,
    CONSTRAINT pk_students PRIMARY KEY (students_id)
);